language: node_js
node_js:
  - "node"
after_success:
  - npm install istanbul
  - npm install coveralls
  - npm run test-cover
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage