language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script: npm test

after_script: istanbul cover jasmine-node --captureExceptions spec/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
